basePath: /v1
host: petstore.swagger.io
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is a sample server Petstore server.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: QB blog Swagger API
  version: "1.0"
paths:
  /api/v1/user/login:
    post:
      consumes:
      - application/json
      description: get accounts
      parameters:
      - description: 用户账号
        in: query
        name: account
        type: string
      - description: 用户密码
        in: query
        name: password
        type: string
      produces:
      - application/json
      summary: 用户登录接口
      tags:
      - accounts
  /api/v1/user/register:
    post:
      consumes:
      - application/json
      description: get accounts
      parameters:
      - description: name search by q
        format: email
        in: query
        name: q
        type: string
      produces:
      - application/json
      summary: 用户注册接口
      tags:
      - accounts
swagger: "2.0"
